apiVersion: v1
kind: Service
metadata:
  labels:
    app: moviecatalog
  name: moviecatalog-svc
  namespace: {{ .Values.namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moviecatalog
  sessionAffinity: None
  type: ClusterIP
