apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-07-04T01:20:24Z"
  labels:
    app: moviecatalog
  name: moviecatalog-svc
  namespace: default
  resourceVersion: "47336"
  uid: 3898d56a-3cbd-4192-b14b-1f9f81174089
spec:
  clusterIP: 10.100.184.100
  clusterIPs:
  - 10.100.184.100
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    nodePort: 31163
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moviecatalog
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}