name: CI/CD
on:
  push: 
      branches: [main]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: gitlab-project

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::151634275520:role/GHA-trust-role
          aws-region: ${{ env.AWS_REGION }}
    
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t $ECR_REPOSITORY:$SHORT_SHA .
      
      - name: Tag image ECR
        run: |
          docker tag $ECR_REPOSITORY:$SHORT_SHA \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$SHORT_SHA
        
      - name: Push image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$SHORT_SHA